#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["test/VoIP_CustomerPortal.API.IntegrationTests/VoIP_CustomerPortal.API.IntegrationTests.csproj", "test/VoIP_CustomerPortal.API.IntegrationTests/"]
COPY ["src/Infrastructure/VoIP_CustomerPortal.Persistence/VoIP_CustomerPortal.Persistence.csproj", "src/Infrastructure/VoIP_CustomerPortal.Persistence/"]
COPY ["src/Core/VoIP_CustomerPortal.Application/VoIP_CustomerPortal.Application.csproj", "src/Core/VoIP_CustomerPortal.Application/"]
COPY ["src/Core/VoIP_CustomerPortal.Domain/VoIP_CustomerPortal.Domain.csproj", "src/Core/VoIP_CustomerPortal.Domain/"]
COPY ["src/API/VoIP_CustomerPortal.Api/VoIP_CustomerPortal.Api.csproj", "src/API/VoIP_CustomerPortal.Api/"]
COPY ["src/Infrastructure/VoIP_CustomerPortal.Infrastructure/VoIP_CustomerPortal.Infrastructure.csproj", "src/Infrastructure/VoIP_CustomerPortal.Infrastructure/"]
COPY ["src/Infrastructure/VoIP_CustomerPortal.Identity/VoIP_CustomerPortal.Identity.csproj", "src/Infrastructure/VoIP_CustomerPortal.Identity/"]
RUN dotnet restore "test/VoIP_CustomerPortal.API.IntegrationTests/VoIP_CustomerPortal.API.IntegrationTests.csproj"
COPY . .
WORKDIR "/src/test/VoIP_CustomerPortal.API.IntegrationTests"
RUN dotnet build "VoIP_CustomerPortal.API.IntegrationTests.csproj" -c Release -o /app/build

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait /wait
RUN chmod +x /wait

# Wait for sql server and then migrate the db and run tests
CMD /wait && dotnet ef database update --context MyDbContext && dotnet test --no-build

FROM build AS publish
RUN dotnet publish "VoIP_CustomerPortal.API.IntegrationTests.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "VoIP_CustomerPortal.API.IntegrationTests.dll"]